
services:
  mongodb:
    image: mongo:latest
    container_name: performance-review-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: performance-review-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongodb:27017/performance-review?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - JWT_EXPIRES_IN=8h
      - WECHAT_CORP_ID=${WECHAT_CORP_ID}
      - WECHAT_AGENT_ID=${WECHAT_AGENT_ID}
      - WECHAT_SECRET=${WECHAT_SECRET}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:5000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: performance-review-frontend
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: